### ISSUE TITLE
 Error changing preferences

### ISSUE THREAD

**Issue by jhosan88** [wirecloud-fiware/ckan-resource-selector-widget#1]
When I change the preferences, the widget shows me this warning:

`TypeError: Cannot read property 'ckan_dataset_source' of undefined
    at loadInitialDataSets (https://mashup.lab.fiware.org/showcase/media/CoNWeT/ckan-resource-selector/1.0.4/js/ckanresourceselector.js:458:13)
    at Widget.prefHandler (https://mashup.lab.fiware.org/showcase/media/CoNWeT/ckan-resource-selector/1.0.4/js/ckanresourceselector.js:227:9)
    at ObjectWithEvents._savePrefs (https://mashup.lab.fiware.org/static/cache/js/f1e3ba739039.js:1350:419)
    at Event.trigger (https://mashup.lab.fiware.org/static/cache/js/f1e3ba739039.js:91:313)
    at Event.dispatch (https://mashup.lab.fiware.org/static/cache/js/f1e3ba739039.js:92:159)
    at StyledElement.acceptHandler (https://mashup.lab.fiware.org/static/cache/js/f1e3ba739039.js:657:162)
    at Event.trigger (https://mashup.lab.fiware.org/static/cache/js/f1e3ba739039.js:91:313)
    at Button.clickCallback (https://mashup.lab.fiware.org/static/cache/js/f1e3ba739039.js:293:19)`

The widget loads and displays the list of datasets, but not the resources of the dataset.

**Comment by aarranz** [comment]
This fix has been release in version [v1.0.5](https://github.com/wirecloud-fiware/ckan-resource-selector-widget/releases/tag/1.0.5) of the widget. We have also uploaded the new version to FIWARE Lab (see the [CKANStarterKit](https://store.lab.fiware.org/offering/CoNWeT/CKANStarterKit/1.2) offering for more info).

Thanks for reporting the problem :)
